import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#FCF5EE',
  '--slot4-page-text': '#850E35',
  '--slot4-panel-bg': '#FFE9E4',
  '--slot4-surface-bg': '#FFFFFF',
  '--slot4-muted-text': '#A6455C',
  '--slot4-soft-muted-text': '#C97A8B',
  '--slot4-accent': '#EE6983',
  '--slot4-accent-fill': '#EE6983',
  '--slot4-accent-soft': '#FFC4C4',
  '--slot4-on-accent': '#FFFFFF',
  '--slot4-dark-bg': '#850E35',
  '--slot4-dark-text': '#FCF5EE',
  '--slot4-media-bg': '#FFC4C4',
  '--slot4-cream': '#FCF5EE',
  '--slot4-warm': '#FFE9E4',
  '--slot4-lavender': '#FFC4C4',
  '--slot4-gray': '#F4D9D2',
  '--slot4-body-gradient': 'linear-gradient(180deg,#FCF5EE 0%,#FFC4C4 45%,#FCF5EE 100%)',
  '--editable-page-bg': '#FCF5EE',
  '--editable-page-text': '#850E35',
  '--editable-container': '1200px',
  '--editable-border': '#F4D9D2',
  '--editable-nav-bg': '#850E35',
  '--editable-nav-text': '#FCF5EE',
  '--editable-nav-active': '#EE6983',
  '--editable-nav-active-text': '#FFFFFF',
  '--editable-cta-bg': '#EE6983',
  '--editable-cta-text': '#FFFFFF',
  '--editable-search-bg': '#FCF5EE',
  '--editable-footer-bg': '#850E35',
  '--editable-footer-text': '#FCF5EE',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-on-accent)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_18px_42px_rgba(40,36,32,0.08)]',
  shadowStrong: 'shadow-[0_24px_70px_rgba(40,36,32,0.18)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(40,36,32,0.04),rgba(40,36,32,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: 'min-h-screen bg-[var(--editable-page-bg)] text-[var(--editable-page-text)]',
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-16 sm:py-20 lg:py-24',
  },
  layout: {
    safeGrid: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-6 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'editable-mono inline-flex items-center gap-2 text-[0.85rem] uppercase leading-[1.4] tracking-[0.12em] text-[var(--slot4-muted-text)] before:h-2 before:w-2 before:rounded-[2px] before:bg-[var(--slot4-accent)]',
    heroTitle: 'editable-display text-[2.8rem] font-normal leading-[1.1] tracking-0 text-white sm:text-[3.5rem] lg:text-[4.25rem]',
    sectionTitle: 'editable-display text-[1.875rem] font-normal leading-[1.15] tracking-0 text-[var(--slot4-page-text)] sm:text-[2.5rem]',
    body: 'text-base leading-[1.5] text-[var(--slot4-muted-text)]',
    emphasis: 'editable-display text-[1.5rem] font-normal leading-[1.2] text-[var(--slot4-page-text)]',
  },
  surface: {
    card: `rounded-[6px] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[6px] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[6px] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: 'inline-flex items-center justify-center gap-2 rounded-[6px] bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-300 hover:brightness-105',
    secondary: 'inline-flex items-center justify-center gap-2 rounded-[6px] border border-white/55 bg-transparent px-6 py-3 text-sm font-semibold text-white transition duration-300 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)]',
    accent: 'inline-flex items-center justify-center gap-2 rounded-[6px] border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-semibold text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-page-text)]',
    ghost: 'inline-flex items-center justify-center gap-2 rounded-[6px] px-4 py-2 text-sm font-semibold text-[var(--slot4-muted-text)] transition duration-300 hover:text-[var(--slot4-page-text)]',
  },
  badge: {
    pill: 'editable-mono inline-flex items-center gap-2 rounded-[6px] border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-3 py-1.5 text-[0.85rem] uppercase tracking-[0.1em] text-[var(--slot4-muted-text)]',
    accentPill: 'editable-mono inline-flex items-center gap-2 rounded-[6px] bg-[var(--slot4-accent-soft)] px-3 py-1.5 text-[0.85rem] uppercase tracking-[0.1em] text-[var(--slot4-page-text)]',
  },
  media: {
    frame: `relative overflow-hidden rounded-[6px] ${editablePalette.mediaBg}`,
    frameFull: `relative overflow-hidden rounded-[6px] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[3/2]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-0.5 hover:shadow-[0_24px_70px_rgba(40,36,32,0.16)]',
    fade: 'transition duration-300 hover:opacity-80',
    zoom: 'transition duration-700 group-hover:scale-[1.03]',
  },
} as const

export const dc = editableDesignContract

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all editable sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use the Insighter reference rhythm: dark rounded media hero, warm editorial bands, compact 6px buttons, mono badges.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
